image:
- Visual Studio 2019
- macOS
- Ubuntu
 
skip_branch_with_pr: true
stack: python 3.10
 
environment:
  GITHUB_TOKEN:
    secure: Ti46nPnZgFh0nRteU6ma0EhJnCTW7PaMn9hnnewZl4gBFPyRQnXNCwGog02+MRLX
 
install:
- pip install -r requirements.txt
 
build_script:
- flet pack main.py --name tickets --icon icon.png --product-name tickets --product-version "1.2.3" --copyright "Copyright (c) 2022 YourCompany Inc."
 
test: off
 
# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    APPVEYOR_REPO_TAG: true
 
#
#   Windows package
# 
for:
-
  matrix:
    only:
    - image: Visual Studio 2019
 
  after_build:
  - 7z a tickets-windows.zip %CD%\dist\*.exe
 
  artifacts:
  - path: tickets-windows.zip
 
#
#   macOS package
# 
-
  matrix:
    only:
    - image: macOS
 
  after_build:
  - tar -czvf tickets-macos.tar.gz -C dist tickets.app
 
  artifacts:
  - path: tickets-macos.tar.gz
 
#
#   Linux package
# 
-
  matrix:
    only:
    - image: Ubuntu
 
  after_build:
  - tar -czvf tickets-linux.tar.gz -C dist counter
 
  artifacts:
  - path: tickets-linux.tar.gz